config/routes.rb
Rails.application.routes.draw do
  #devise
  devise_for :owners, controller: {
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    registrations: "owners/registration"
    }

  devise_for :customers, controller: {
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    registrations: "customers/registration"
    }
  
  #top,about
  get 'owners/top' => 'owners#top'
  root 'home#top'
  get 'home/about' => 'home#about'


  #owner_side

  namespace :owners do
    #items
    resources :items, only: [:new, :create, :edit, :update]
    get 'items/index_owner'    =>  'items#index_owner'
    get 'items/:id/show_owner' =>  'items#show_owner'
    
    #genre
    resources :genres, only: [:index, :create, :edit, :update]
    
    #customers
    resources :customers, only: [:index]
    get 'customers/:id/show_owner'      => 'customers#show_owner' , as: :show_owner_costomer
    get 'customers/:id/edit/edit_owner' => 'customers#edit_owner', as: :edit_owner_costomer
    patch 'customers/:id/update_owner'  => 'customers#update_owner', as: :update_owner_costomer

    #orders
    resources :orders, only: [:index, :show, :update]
    patch 'order/:id/update_order' => 'orders#update_order',as: :update_owner_order
  end


  #customer_side
  
  #items
  namespace :customers do
    resources :items, only: [:index, :show]
  end

  scope module: :customers do
    #customers_1
    get 'customers/:id/leave' => 'customers#leave', as: :leave
    patch 'customers/out' => 'customers#out'

    #orders_1
    get '/customers/:customer_id/orders/thanks' => 'orders#thanks'
    post '/customers/:customer_id/orders/confirm' => 'orders#confirm', as: :confirm
    get '/customers/:customer_id/orders/:id/complete' => 'orders#complete', as: :complete

    #customers_2
    resources :customers, only: [:show, :edit, :update] do
      #cart_items
      delete 'cart_items' => 'cart_items#all_destroy'
      resources :cart_items, only: [:create, :index, :update, :destroy]
      
      #shipping_addresses
      resources :shipping_addresses , only: [:index,  :create, :edit, :update, :destroy]
      
      #orders_2
      resources :orders, only: [:index, :show, :new, :create]
    end
    
    
  end
  
  
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	has_many :customers, through: :cart_items # 中間テーブルのアソシエーション定義
	has_many :order_items, dependent: :destroy
	has_many :orders, through: :order_items # 中間テーブルのアソシエーション定義

	validates :name, presence: true
	validates :content, presence: true
	validates :no_tax_price, presence: true
	
	enum sale_status: { unavailable: 0, available: 1}
	validates :sale_status, inclusion: { in: Item.sale_statuses.keys }
  
	attachment :image
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  before_action :authenticate_customer!
  
  def index
    if params[:genre_nav].blank?
      # 商品一覧
      @genres = Genre.where(status: true)
      @items_count = Item.all.count
      @items = Item.page(params[:page]).per(8)
      @title = "商品"
    else
      # ジャンル一覧
      @genres = Genre.where(status: true)
      @genre = Genre.find(params[:genre_nav])
      @items_count = Item.where(genre_id: params[:genre_nav]).count
      @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
      @title = @genre.name
    end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.where(status: true)
  end

end

app/controllers/owners/customers_controller 2.rb
class Owners::CustomersController < ApplicationController

def index
end

def show_owner
end

def edit_owner
end

def update_owner
end

end

app/controllers/owners/customers_controller.rb
class Owners::CustomersController < ApplicationController
  before_action :authenticate_owner!

def index
  @customer = Customer.all
  @customers = Customer.all.page(params[:page]).per(10)
end

def show_owner
	@customer = Customer.find(params[:id])
end

def edit_owner
  @customer = Customer.find(params[:id])
end

def update_owner
  @customer = Customer.find(params[:id])
  @customer.update(customers_params)
  if @customer.save
    redirect_to owners_customers_path
    end
end

private
    def customers_params
      params.require(:customer).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :postal_code,:address, :telephone_number, :status)
    end
end

app/controllers/owners/genres_controller 2.rb
class Owners::GenresController < ApplicationController

def index
end

def create
end

def edit
end

def update
end

end

app/controllers/owners/genres_controller.rb
class Owners::GenresController < ApplicationController
  before_action :authenticate_owner!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンル登録完了しました！"
      redirect_to owners_genres_path
    else
      flash[:notice] = "更新に失敗しました。入力を確認してください。"
      @genre = Genre.all
      redirect_to owners_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.save
      flash[:notice] = "カテゴリーを更新しました"
      redirect_to owners_genres_path# 一覧画面へリダイレクト
    else
      render :edit

    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/owners/items_controller 2.rb
class Owners::ItemsController < ApplicationController

def new
end

def create
end

def index_owner
end

def show_owner
end

def edit
end

def update
end

end

app/controllers/owners/items_controller.rb
class Owners::ItemsController < ApplicationController
  before_action :authenticate_owner!

  def new
    @item = Item.new
    @genres = Genre.where(status: true)
  end

  def create
    @item = Item.new(items_params)
    if @item.save
      flash[:notice] = "商品登録完了しました！"
      redirect_to owners_path(@item)
    else
      @genres = Genre.where(status: true)
      render 'new'
    end
  end

  def index_owner
    @item = Item.all
    @items = Item.all.page(params[:page]).per(10)
  end

  def show_owner
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(items_params)
    if @item.save
    flash[:notice] = "商品登録更新しました！"
    redirect_to owners_items_index_owner_path# 一覧画面へリダイレクト
    
  end
  end


  private
  def items_params
    params.require(:item).permit(:name, :content, :no_tax_price, :sale_status, :image ,:genre_id)
  end
end

app/controllers/owners/orders_controller 2.rb
class Owners::OrdersController < ApplicationController

def index
end

def show
end

def update_order
end

def update
end

end

app/controllers/owners/orders_controller.rb
class Owners::OrdersController < ApplicationController
  before_action :authenticate_owner!

	def index
		case params[:order_index_source]
			when "from_header"
				@orders = Order.all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_top"
				@orders = Order.where(created_at: Time.zone.now.all_day).page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_show_owner"
				@orders = Order.where(customer_id: params[:customer_source]).all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
		end
	end

	def show
		@order = Order.find(params[:id])
		@sum = 0
	end

	def update
		@order = Order.find(params[:id])
		@order.update(orders_params)
			if params[:order][:status] == "payment_confirm"
				@order.order_items.each do |order_item|
					order_item.standby_making!
				end
				flash[:notice] = "注文の入金が確認できたので、商品の製品ステータスを製作待ちに更新しました！"
			else
				flash[:notice] = "注文ステータスを更新しました！"
			end
		redirect_to owners_order_path(@order.id)
	end
	
	def update_order
		@order = Order.find(params[:order_item][:order_id])
		@order_item = OrderItem.find(params[:id])
		@order_items = OrderItem.where(order_id: params[:order_item][:order_id])		
		@order_item.item_status = params[:order_item][:item_status]
		@order_item.update(order_item_params)
		if @order_items.where(item_status: "making").count == 1 && @order_items.where(item_status: "making_finish").count != @order_items.count - 1
			@order.making!
			flash[:notice] = "製作ステータスおよび注文ステータスを製作中に更新しました！"
		end
		if @order_items.where(item_status: "making_finish").count == @order_items.count
			@order.ready_to_ship!
			flash[:notice] = "注文された商品の製作が完了したので、注文ステータスを発送準備中に更新しました！"
		else
			flash[:notice] = "商品の製作ステータスを更新しました！"
		end			
		redirect_to owners_order_path(@order.id)
	end

	private
	def orders_params
		params.require(:order).permit(:customer_id, :postage, :billing_amount, :payment, :address, :postal_code, :status, :address_name)
	end
	def order_item_params
		params.require(:order_item).permit(:item_status)
	end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def top
		if Order.where(created_at: Time.zone.now.all_day).present?
			@data = Order.where(created_at: Time.zone.now.all_day).count
		end
	end

end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/owners/customers_helper 2.rb
module Owners::CustomersHelper
end

app/helpers/owners/customers_helper.rb
module Owners::CustomersHelper
end

app/helpers/owners/genres_helper 2.rb
module Owners::GenresHelper
end

app/helpers/owners/genres_helper.rb
module Owners::GenresHelper
end

app/helpers/owners/items_helper 2.rb
module Owners::ItemsHelper
end

app/helpers/owners/items_helper.rb
module Owners::ItemsHelper
end

app/views/owners/items/edit.html.erb
<h3 class="ow_ganre_title">商品編集</h3>
  <div class="row" style="margin-top:50px;">
    <!-- エラーメッセージ -->
    <%= form_with(model:@item, url:	owners_item_path, method: :patch , local: true ) do |f| %>
      <% if @item.errors.any? %>
        <div class="error_explanation">
          <h3><%= @item.errors.count %>error prohibited this obj from being saved:</h3>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
			</div>
			<% end %>

    <!-- 商品イメージ写真編集 -->
      <div class = "col-lg-4">
        <%= attachment_image_tag @item, :image,format: 'jpeg', size: "300x300", fallback: "no_image.jpg"%>
        <%= f.attachment_field :image, placeholder: "商品画像" %>
      </div>

    <!-- 商品詳細編集フォーム -->
      <div class = "col-lg-4">
        <br><br><%= f.label :name, "商品名" ,class: "col-sm-5"%>
        <%= f.text_field :name %>
        <br><br><%= f.label :content, "商品説明" ,class: "col-sm-5"%>
        <%= f.text_area :content %>
        <br><br><%= f.label :genre_id, "ジャンル" ,class: "col-sm-5"%>
        <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい"  %>
        <br><br><%= f.label :no_tax_price, "税抜き価格" ,class: "col-sm-5"%>
        <%= f.text_field :no_tax_price %>
        <br><br><%= f.label :sale_status, "販売ステータス" ,class: "col-sm-5"%>
        <%= f.select :sale_status, [["販売中止","unavailable"], ["販売中","available"]], include_blank: "選択して下さい"  %>
      </div>
      <div class = "col-lg-3 newaction">
			  <br><%= f.submit'変更を保存',class: "btn btn-primary px-3" %>
			</div>
    <% end %>
  </div>
</div>

app/views/owners/items/index_owner.html.erb
<h3 class="ow_ganre_title">商品一覧</h3>
  <div class="row">
    <!-- 商品追加ボタン -->
    <%= link_to'', new_owners_item_path,class:"fas fa-plus-circle fa-4x" %>

    <!-- 商品一覧テーブル -->
    <div class = "col-lg-11">
      <table class="table table-hover table-bordered table-condensed">
        <thead>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </thead>
        <% @item.each do |item| %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= link_to item.name, owners_path(item) %>
            </td>
            <td>
              <%= item.no_tax_price.to_s(:delimited, delimiter: ',')%>
            </td>
            <td>
              <%= item.genre.name %>
            </td>
            <td>
              <% if item.sale_status == "available" %>
                販売中
              <% else %>
                販売中止
              <% end %>
            </td>
        <% end %>
      </table>
    </div>
  </div>
  <%= paginate @items %>

app/views/owners/items/new.html.erb
<h3 class="ow_ganre_title">商品新規登録</h3>
	<div class="row">
		<!-- エラ〜メッセージ -->
		<%= form_with(model:@item, url:	owners_items_path, method: :post , local: true ) do |f| %>
			<% if @item.errors.any? %>
				<div class="error_explanation">
					<h3><%= @item.errors.count %>error prohibited this obj from being saved:</h3>
					<ul>
						<% @item.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>

		<!-- 画像登録フォーム -->
			<div class = "col-lg-5">
				<%= attachment_image_tag @item, :image, :fill, 60, 60 %>
				<%= f.attachment_field :image, placeholder: "商品画像" %>
			</div>

		<!-- 商品情報登録フォーム -->
			<div class = "col-lg-4">
				<br><br><%= f.label :name, "商品名" %>
					<%= f.text_field :name %>
				<br><br><%= f.label :content, "商品説明" %>
					<%= f.text_area :content %>
				<br><br><%= f.label :genre_id, "ジャンル" %>
					<%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい"  %>
				<br><br><%= f.label :no_tax_price, "税抜き価格" %>
					<%= f.text_field :no_tax_price %>
				<br><br><%= f.label :sale_status, "販売ステータス" %>
					<%= f.select :sale_status, [["販売中止","unavailable"], ["販売中","available"]], include_blank: "選択して下さい"  %>
			</div>
			<div class = "col-lg-3 newaction">
			<br><br><%= f.submit'新規登録',class: "btn btn-primary px-3" %>
			</div>
		<% end %>
	</div>

app/views/owners/items/show_owner.html.erb
<h4 class="ow_ganre_title">商品詳細</h4>
  <div class="row" style="margin-top:50px;">
    <div class = "col-lg-1">
    </div>

    <!-- 商品イメージ写真 -->
    <div class = "col-lg-3">
      <%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x300", fallback: "no_image.jpg"%>
    </div>

    <div class = "col-lg-2">
    </div>

    <!-- 商品ステータス一覧 -->
    <div class = "col-lg-2">
      <br><h5>商品名</h5>
      <br><h5>商品説明</h5>
      <br><h5>ジャンル</h5>
      <br><h5>税込価格(税抜価格)</h5>
      <br><h5>販売ステータス</h5>
    </div>

    <!-- 商品情報一覧 -->
    <div class = "col-lg-4">
      <br><h5><%= @item.name %></h5>
      <br><h5><%= @item.content %></h5>
      <br><h5><%= @item.genre.name %></h5>
      <br><h5><%= (@item.no_tax_price * 1.1 ).floor.to_s(:delimited, delimiter: ',') %>円(<%= @item.no_tax_price.to_s(:delimited, delimiter: ',') %>円)</h5>
      <br><h5><% if @item.sale_status == "available" %>
                販売中
              <% else %>
                販売中止
              <% end %>
          </h5>
      <br><h5><%= link_to "編集する",edit_owners_item_path(@item) %></h5>
    </div>
  </div>