config/routes.rb
Rails.application.routes.draw do
  #devise
  devise_for :owners, controller: {
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    registrations: "owners/registration"
    }

  devise_for :customers, controller: {
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    registrations: "customers/registration"
    }
  
  #top,about
  get 'owners/top' => 'owners#top'
  root 'home#top'
  get 'home/about' => 'home#about'


  #owner_side

  namespace :owners do
    #items
    resources :items, only: [:new, :create, :edit, :update]
    get 'items/index_owner'    =>  'items#index_owner'
    get 'items/:id/show_owner' =>  'items#show_owner'
    
    #genre
    resources :genres, only: [:index, :create, :edit, :update]
    
    #customers
    resources :customers, only: [:index]
    get 'customers/:id/show_owner'      => 'customers#show_owner' , as: :show_owner_costomer
    get 'customers/:id/edit/edit_owner' => 'customers#edit_owner', as: :edit_owner_costomer
    patch 'customers/:id/update_owner'  => 'customers#update_owner', as: :update_owner_costomer

    #orders
    resources :orders, only: [:index, :show, :update]
    patch 'order/:id/update_order' => 'orders#update_order',as: :update_owner_order
  end


  #customer_side
  
  #items
  namespace :customers do
    resources :items, only: [:index, :show]
  end

  scope module: :customers do
    #customers_1
    get 'customers/:id/leave' => 'customers#leave', as: :leave
    patch 'customers/out' => 'customers#out'

    #orders_1
    get '/customers/:customer_id/orders/thanks' => 'orders#thanks'
    post '/customers/:customer_id/orders/confirm' => 'orders#confirm', as: :confirm
    get '/customers/:customer_id/orders/:id/complete' => 'orders#complete', as: :complete

    #customers_2
    resources :customers, only: [:show, :edit, :update] do
      #cart_items
      delete 'cart_items' => 'cart_items#all_destroy'
      resources :cart_items, only: [:create, :index, :update, :destroy]
      
      #shipping_addresses
      resources :shipping_addresses , only: [:index,  :create, :edit, :update, :destroy]
      
      #orders_2
      resources :orders, only: [:index, :show, :new, :create]
    end
    
    
  end
  
  
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items # 中間テーブルのアソシエーション定義
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_furigana, presence: true
  validates :first_furigana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, uniqueness: true


  enum status: { unavailable: 0, available: 1}
  validates :status, inclusion: { in: Customer.statuses.keys }

  def active_for_authentication?
    super && (self.status == "available")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items # 中間テーブルのアソシエーション定義

  validates :address, presence: true
  validates :address_name, presence: true
  validates :postal_code, presence: true

  enum payment: { credit_card: 0, bank_transfer: 1 }
  validates :payment, inclusion: { in: Order.payments.keys }

  enum status: { waiting_payment: 0, payment_confirm: 1, making: 2, ready_to_ship: 3, shipped: 4 }
  validates :status, inclusion: { in: Order.statuses.keys }
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
	before_action :authenticate_customer!

  def index
    @items = current_customer.items
    @cart_items = current_customer.cart_items
	end

  def create
    @cart_item = current_customer.cart_items.build(cart_item_params)
    if CartItem.find_by(item_id: @cart_item.item_id).nil?
      @cart_item.save
      flash[:notice] = "商品をカートに追加しました。"
    else
      cart_item = CartItem.find_by(item_id: @cart_item.item_id)
      cart_item.number += params[:cart_item][:number].to_i
      cart_item.save(cart_item_params)
      flash[:notice] = "カート内既存商品の数量を変更しました。"
    end
    redirect_to customer_cart_items_path(current_customer.id)
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.number = params[:cart_item][:number]
    if @cart_item.update(cart_item_params)
      if current_customer.cart_items.where(number: 0).present?
        current_customer.cart_items.where(number: 0).destroy_all
        flash[:notice] = "カートの商品を削除しました"
      else
        flash[:notice] = "商品の数量を変更しました。"
      end
      redirect_to customer_cart_items_path(current_customer.id)
    end
	end

  def destroy
    cart_item = CartItem.find_by(params[:id])
    if cart_item.destroy
      flash[:notice] = "カートの商品を削除しました。"
      redirect_to customer_cart_items_path(current_customer.id)
    end    
	end

  def all_destroy
    cart_items = CartItem.where(customer_id: current_customer.id)    
    if cart_items.destroy_all
      flash[:notice] = "カートを空にしました。"
      redirect_to customer_cart_items_path(current_customer.id)
    end
	end
  
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :customer_id, :number)
  end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
	before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
  end
  
  def out
    @customer = Customer.find(params[:customer_out_id])
    @customer.unavailable!
    if @customer.status == "unavailable"
      flash[:success] = "退会処理が完了しました。ご利用ありがとうございました。"
      redirect_to root_path
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customers_params)
      flash[:success] = "ユーザ情報の更新に成功しました！"
      redirect_to customer_path(@customer.id)
    else
      render "edit"
    end
  end

  private
  def customers_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :postal_code,:address,:telephone_number)
  end
  
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  before_action :authenticate_customer!
  
  def index
    if params[:genre_nav].blank?
      # 商品一覧
      @genres = Genre.where(status: true)
      @items_count = Item.all.count
      @items = Item.page(params[:page]).per(8)
      @title = "商品"
    else
      # ジャンル一覧
      @genres = Genre.where(status: true)
      @genre = Genre.find(params[:genre_nav])
      @items_count = Item.where(genre_id: params[:genre_nav]).count
      @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
      @title = @genre.name
    end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.where(status: true)
  end

end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders
  end

  def create
    if current_customer.cart_items.exists?
      #お届け先によって保存内容を場合分け
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.address_name = params[:order][:address_name]
      @order.billing_amount = params[:order][:billing_amount]
      @order.save

      #今回使われた配送先が新規のものであれば、配送先に新規登録
      if ShippingAddress.find_by(shipping_address: @order.address).nil? && current_customer.address != @order.address
        @shipping_address = ShippingAddress.new
        @shipping_address.shipping_postal_code = @order.postal_code
        @shipping_address.shipping_address = @order.address
        @shipping_address.address_name = @order.address_name
        @shipping_address.customer_id = current_customer.id
        @shipping_address.save
      end

      #cart_itemsの内容をorder_itemsに新規登録
      current_customer.cart_items.each do |cart_item|
        order_item = @order.order_items.build
        order_item.order_id = @order.id
        order_item.item_id = cart_item.item_id
        order_item.number = cart_item.number
        order_item.buy_price = (cart_item.item.no_tax_price * 1.1).floor
        order_item.save
        cart_item.destroy #order_itemsに新規登録後はカートの中を空にする
      end
      redirect_to complete_path(current_customer.id, @order.id)
    else
      redirect_to root_path
      flash[:danger] = "カートが空です。"
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @items = @order.items
  end

  def new
    @order = Order.new
    @shipping_addresses = ShippingAddress.where(customer_id: current_customer.id)
  end

  def confirm    
    #注文情報入力画面でのお届け先選択によって分岐
    @order = Order.new
    if params[:choice_shipping_address] == "my_address"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.address_name = current_customer.last_name + current_customer.first_name
      @cart_items = current_customer.cart_items

    elsif params[:choice_shipping_address] == "registered_address"
      @shipping_address = ShippingAddress.find(params[:choice_pulldown])
      @order.postal_code = @shipping_address.shipping_postal_code
      @order.address = @shipping_address.shipping_address
      @order.address_name = @shipping_address.address_name
      @cart_items = current_customer.cart_items

    else
      @order.postal_code = params[:postal_code]
      @order.address = params[:address]
      @order.address_name = params[:address_name]
      @cart_items = current_customer.cart_items
    end
  end
  
  def complete
  end

  private
  def order_params
    params.require(:order).permit(:payment, :address_name, :address, :postal_code, :choice_pulldown)
  end
end

app/controllers/customers/shipping_addresses_controller.rb
class Customers::ShippingAddressesController < ApplicationController
	before_action :authenticate_customer!

	def index
		@shipping_address = ShippingAddress.new
		@shipping_addresses = ShippingAddress.where(customer_id: current_customer.id)
	end

	def create
		# Customer、Shipping_addressそれぞれのアドレス情報を検索して、存在しない場合のみShipping_addressに登録
		if (current_customer.postal_code != params[:shipping_address][:shipping_postal_code] && current_customer.address != params[:shipping_address][:shipping_address] && current_customer.last_name + current_customer.first_name != params[:shipping_address][:address_name]) && (current_customer.shipping_addresses.where(shipping_postal_code: params[:shipping_address][:shipping_postal_code], shipping_address: params[:shipping_address][:shipping_address], address_name: params[:shipping_address][:address_name]).blank?)

			@shipping_address = ShippingAddress.new(shipping_address_params)
			@shipping_address.customer_id = current_customer.id
			if @shipping_address.save
				flash[:success] = "配送先の作成に成功しました！"
			else
				@shipping_addresses = ShippingAddress.where(customer_id: current_customer.id)
				render "index" and return
			end
		else
			flash[:notice] = "既に登録されている配送先、もしくはご自身の住所と同一です。ご自身の住所の変更はマイページから行ってください。"
		end
		@shipping_address = ShippingAddress.new
		redirect_to customer_shipping_addresses_path(current_customer.id)
	end

	def destroy
		@shipping_address = ShippingAddress.find(params[:id])
		if @shipping_address.destroy
      flash[:success] = "配送先の削除に成功しました！"
      redirect_to customer_shipping_addresses_path
    end
	end

	def edit
    @shipping_address = ShippingAddress.find(params[:id])
	end
	
	def update
		@shipping_address = ShippingAddress.find(params[:id])
		if @shipping_address.update(shipping_address_params)
      flash[:success] = "配送先の更新に成功しました！"
      redirect_to customer_shipping_addresses_path(current_customer.id)
		else
      render :edit
		end
	end

	private
	def shipping_address_params
		params.require(:shipping_address).permit(:address_name,:shipping_address,:shipping_postal_code)
	end
end

app/controllers/owners/customers_controller.rb
class Owners::CustomersController < ApplicationController
  before_action :authenticate_owner!

def index
  @customer = Customer.all
  @customers = Customer.all.page(params[:page]).per(10)
end

def show_owner
	@customer = Customer.find(params[:id])
end

def edit_owner
  @customer = Customer.find(params[:id])
end

def update_owner
  @customer = Customer.find(params[:id])
  @customer.update(customers_params)
  if @customer.save
    redirect_to owners_customers_path
    end
end

private
    def customers_params
      params.require(:customer).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :postal_code,:address, :telephone_number, :status)
    end
end

app/controllers/owners/orders_controller.rb
class Owners::OrdersController < ApplicationController
  before_action :authenticate_owner!

	def index
		case params[:order_index_source]
			when "from_header"
				@orders = Order.all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_top"
				@orders = Order.where(created_at: Time.zone.now.all_day).page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_show_owner"
				@orders = Order.where(customer_id: params[:customer_source]).all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
		end
	end

	def show
		@order = Order.find(params[:id])
		@sum = 0
	end

	def update
		@order = Order.find(params[:id])
		@order.update(orders_params)
			if params[:order][:status] == "payment_confirm"
				@order.order_items.each do |order_item|
					order_item.standby_making!
				end
				flash[:notice] = "注文の入金が確認できたので、商品の製品ステータスを製作待ちに更新しました！"
			else
				flash[:notice] = "注文ステータスを更新しました！"
			end
		redirect_to owners_order_path(@order.id)
	end
	
	def update_order
		@order = Order.find(params[:order_item][:order_id])
		@order_item = OrderItem.find(params[:id])
		@order_items = OrderItem.where(order_id: params[:order_item][:order_id])		
		@order_item.item_status = params[:order_item][:item_status]
		@order_item.update(order_item_params)
		if @order_items.where(item_status: "making").count == 1 && @order_items.where(item_status: "making_finish").count != @order_items.count - 1
			@order.making!
			flash[:notice] = "製作ステータスおよび注文ステータスを製作中に更新しました！"
		end
		if @order_items.where(item_status: "making_finish").count == @order_items.count
			@order.ready_to_ship!
			flash[:notice] = "注文された商品の製作が完了したので、注文ステータスを発送準備中に更新しました！"
		else
			flash[:notice] = "商品の製作ステータスを更新しました！"
		end			
		redirect_to owners_order_path(@order.id)
	end

	private
	def orders_params
		params.require(:order).permit(:customer_id, :postage, :billing_amount, :payment, :address, :postal_code, :status, :address_name)
	end
	def order_item_params
		params.require(:order_item).permit(:item_status)
	end
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/customer/shipping_addresses_helper.rb
module Customer::ShippingAddressesHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/owners/customers_helper.rb
module Owners::CustomersHelper
end

app/helpers/owners/orders_helper.rb
module Owners::OrdersHelper
end

app/views/customers/orders/complete.html.erb
<div class="ec_order_complete_text">
	<h1>ご購入ありがとうございました！</h1>
</div>

app/views/customers/orders/confirm.html.erb
<div class="row ec_order_confirm_body">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<!-- 画面表示部分 -->
		<div>
			<h3 class="ec_order_confirm_title">　注文情報確認　</h3>
		</div>
	</div>
</div>

<div class="row ec_order_confirm_table">
	<div class="col-xs-2"></div>
	<div class="col-xs-6">
		<div>
			<table class="table table-bordered">
				<thead>
					<tr class="active">
						<th>商品名</th>
						<th>単価（税込）</th>
						<th>数量</th>
						<th>小計</th>
					</tr>
				</thead>
				<tbody>
					<% @cart_items_total_price = 0  %>
					<% @cart_items.each do |cart_item| %>
					<tr>
						<td><%= attachment_image_tag(cart_item.item, :image, :fill, 80, 60) %>　<%= cart_item.item.name %></td>
						<td><%= (cart_item.item.no_tax_price * 1.1).floor.to_s(:delimited, delimiter: ',') %></td>
						<td><%= cart_item.number %></td>
						<td><%= ((cart_item.item.no_tax_price * 1.1).floor * (cart_item.number)).to_s(:delimited, delimiter: ',') %></td>
					</tr>
						<% @cart_items_total_price += (cart_item.item.no_tax_price * 1.1).floor * (cart_item.number) %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<div class="col-xs-3">
		<div>
			<table class="table table-bordered">
				<tbody>
					<tr>
						<td class="active">送料</td>
						<td><%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
					</tr>
					<tr>
						<td class="active">商品合計</td>
						<td><%= @cart_items_total_price.to_s(:delimited, delimiter: ',') %></td>
					</tr>
					<tr>
						<td class="active">請求金額</td>
						<td><%= ((@cart_items_total_price) + (@order.postage)).to_s(:delimited, delimiter: ',')  %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-xs-1"></div>
</div>

<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h4><b>支払方法</b></h4>
			<% if params[:payment] == "credit_card" %>
				<p class="ec_order_confirm_payment">クレジットカード</p>
			<% else %>
				<p class="ec_order_confirm_payment">銀行振込</p>
			<% end %>
		</div>

		<div>
			<h4><b>お届け先</b></h4>
			<% if params[:choice_shipping_address] == "my_address" %>
				<p class="ec_order_confirm_shipping_address"><%= current_customer.postal_code %>　<%= current_customer.address %>　<%= current_customer.last_name %><%= current_customer.first_name %></p>
			<% else %>
				<p class="ec_order_confirm_shipping_address"><%= @order.postal_code %>　<%= @order.address %>　<%= @order.address_name %></p>
			<% end %>
		</div>
	
		<!-- 注文情報送信部分 -->
		<%= form_with(model: @order, url: customer_orders_path(current_customer.id), method: :post, local: true) do |f| %>
			<%= f.hidden_field :payment, value: params[:payment] %>
			<%= f.hidden_field :billing_amount, value: (@cart_items_total_price) + (@order.postage) %>
			<!-- お届け先によってパラメータを場合分け -->
			<% if params[:choice_shipping_address] == "my_address" %>
				<%= f.hidden_field :postal_code, value: current_customer.postal_code %>
				<%= f.hidden_field :address, value: current_customer.address %>
				<%= f.hidden_field :address_name, value: (current_customer.last_name) + (current_customer.first_name) %>
			<% else %>
				<%= f.hidden_field :postal_code, value: @order.postal_code %>
				<%= f.hidden_field :address, value: @order.address %>
				<%= f.hidden_field :address_name, value: @order.address_name %>
			<% end %>

			<%= f.submit "　購入を確定する　", class: "btn btn-success ec_order_confirm_button" %>
		<% end %>
	</div>
</div>

app/views/customers/orders/index.html.erb
<!-- 注文がなかった場合 -->
<% if @orders.blank? %>
  <p>履歴はありません</p>
<% else %>
  <div class="cart_title">
    <h2>注文履歴一覧</h2>
  </div>

<!-- 注文履歴一覧 -->
  <div class="shopping_cart">
    <table class="cart_table">
      <tr>
        <th>注文日</th>
        <th>配送先</th>
        <th>注文商品</th>
        <th>支払金額</th>
        <th>ステータス</th>
        <th>注文詳細</th>
      </tr>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= simple_time(order.created_at) %>
          </td>
          <td>
            <%= order.postal_code %><br>
            <%= order.address %><br>
            <%= order.address_name %>
          </td>
          <td>
            <% order.items.each do |item| %>
              <%= item.name %><br>
            <% end %>
          </td>
          <td>
            <%= order.billing_amount.to_s(:delimited, delimiter: ',') %> 円
          </td>
          <td>
            <% case order.status %>
              <% when "waiting_payment" %>
                入金待ち
              <% when "payment_confirm" %>
                入金確認
              <% when "making" %>
                製作中
              <% when "ready_to_ship" %>
                発送準備中
              <% when "shipped" %>
                発送済み
            <% end %>
          </td>
          <td class="cart_item_btn">
            <%= link_to  "表示する", customer_order_path(current_customer.id, order.id) %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/customers/orders/new.html.erb
<div class="row ec_order_new_body">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h3 class="ec_order_new_title">　注文情報入力　</h3>
		</div>
		<div>
			<%= form_with(url: confirm_path(current_customer.id), method: :post, local: true) do |f| %>
				<!-- 支払方法 -->
				<h4 class="ec_order_new_form_title">支払方法</h4>
				<div class="field form-group">
					<%= f.radio_button :payment, :credit_card, checked: true %>
					<%= f.label :payment, "クレジットカード", {value: :credit_card} %>
				</div>
				<div class="field form-group">
					<%= f.radio_button :payment, :bank_transfer %>
					<%= f.label :payment, "銀行振込", {value: :bank_transfer} %>
				</div>

				<h4 class="ec_order_new_form_title">お届け先</h4>
				<!-- 自身の住所 -->
				<div class="ec_order_new_form">
					<%= f.radio_button :choice_shipping_address, :my_address, checked: true %>
					<%= f.label :choice_shipping_address, "ご自身の住所", {value: :my_address} %>
				</div>
				<div class="ec_order_new_form_body">
					<%= current_customer.postal_code %>　<%= current_customer.address %><br>
					<%= current_customer.last_name %><%= current_customer.first_name %>
				</div>

				<!-- 登録済住所 -->
				<div class="field form-group ec_order_new_form">
					<%= f.radio_button :choice_shipping_address, :registered_address %>
					<%= f.label :choice_shipping_address, "登録済住所から選択", {value: :registered_address} %>
				</div>
				<div class="field form-group ec_order_new_form ec_order_new_form_body">
					<%= f.collection_select(:choice_pulldown, @shipping_addresses, :id, :registered_shipping_address) %>
				</div>

				<!-- 新しい住所 -->
				<div class="field form-group ec_order_new_form">
					<%= f.radio_button :choice_shipping_address, :new_address %>
					<%= f.label :choice_shipping_address, "新しいお届け先", {value: :new_address} %>
				</div>
				<div class="field form-group ec_order_new_form ec_order_new_form_body">
					<%= f.label :postal_code, "郵便番号（ハイフンなし）　" %>
					<%= f.text_field :postal_code %>
				</div>
				<div class="field form-group ec_order_new_form ec_order_new_form_body">
					<%= f.label :address, "住所　　　　　　　　　　　" %>
					<%= f.text_field :address, :size => "50" %>
				</div>
				<div class="field form-group ec_order_new_form ec_order_new_form_body">
					<%= f.label :address_name, "宛名　　　　　　　　　　　" %>
					<%= f.text_field :address_name %>
				</div>

				<%= f.submit "　確認画面へ進む　", class: "btn btn-primary ec_order_new_form_button" %>

			<% end %>
		</div>
	</div>
</div>

app/views/customers/orders/show.html.erb
<div class="cart_title">
  <h2>注文履歴詳細</h2>
</div>

<div class="ec_order_flex">
  <!-- 注文情報欄 -->
  <div class="ec_order_information">
    <h2>注文情報</h2>
    <dl>
      <dt>注文日</dt>
      <dd><%= simple_time(@order.created_at) %></dd>
      <dt>配送先</dt>
      <dd><%= @order.address %></dd>
      <dt>支払方法</dt>
      <dd>
        <% case @order.payment %>
          <% when "credit_card" %>
            クレジットカード
          <% when "bank_transfer" %>
            銀行振込
        <% end %>
      </dd>
      <dt>ステータス</dt>
      <dd>
        <% case @order.status %>
          <% when "waiting_payment" %>
            入金待ち
          <% when "payment_confirm" %>
            入金確認
          <% when "making" %>
            製作中
          <% when "ready_to_ship" %>
            発送準備中
          <% when "shipped" %>
            発送済み
        <% end %>
      </dd>
    </dl>
  </div>

  <!-- 請求情報欄 -->
  <div class="ec_order_information">
    <h2>請求情報</h2>
    <dl>
      <dt>商品合計</dt>
      <dd>
        <% @total_price = 0 %>
        <% @order_items.each do |order_item| %>
          <% @total_price += order_item.buy_price * order_item.number %>
        <% end %>
        <%= @total_price.to_s(:delimited, delimiter: ',')%>
      </dd>
      <dt>配送料</dt>
      <dd><%= @order.postage.to_s(:delimited, delimiter: ',') %></dd>
      <dt>ご請求額</dt>
      <dd><%= @order.billing_amount.to_s(:delimited, delimiter: ',') %></dd>
    </dl>
  </div>
</div>

<div class="ec_order_information">
  <!-- 注文内容欄 -->
  <table class="cart_table">
    <caption>注文内容</caption>
    <tr>
      <th>商品</th>
      <th>単価（税込）</th>
      <th>個数</th>
      <th>小計</th>
    </tr>
    <% @items.zip(@order_items).each do |item, order_item| %>
      <tr>
        <td>
          <%= item.name %>
        </td>
        <td>
          <%= ( item.no_tax_price * 1.1 ).floor.to_s(:delimited, delimiter: ',') %>
        </td>
        <td>
          <%= order_item.number %>
        </td>
        <td>
          <%= (( item.no_tax_price * 1.1 ).floor * order_item.number).to_s(:delimited, delimiter: ',') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>