config/routes.rb
Rails.application.routes.draw do
  #devise
  devise_for :owners, controller: {
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    registrations: "owners/registration"
    }

  devise_for :customers, controller: {
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    registrations: "customers/registration"
    }
  
  #top,about
  get 'owners/top' => 'owners#top'
  root 'home#top'
  get 'home/about' => 'home#about'


  #owner_side

  namespace :owners do
    #items
    resources :items, only: [:new, :create, :edit, :update]
    get 'items/index_owner'    =>  'items#index_owner'
    get 'items/:id/show_owner' =>  'items#show_owner'
    
    #genre
    resources :genres, only: [:index, :create, :edit, :update]
    
    #customers
    resources :customers, only: [:index]
    get 'customers/:id/show_owner'      => 'customers#show_owner' , as: :show_owner_costomer
    get 'customers/:id/edit/edit_owner' => 'customers#edit_owner', as: :edit_owner_costomer
    patch 'customers/:id/update_owner'  => 'customers#update_owner', as: :update_owner_costomer

    #orders
    resources :orders, only: [:index, :show, :update]
    patch 'order/:id/update_order' => 'orders#update_order',as: :update_owner_order
  end


  #customer_side
  
  #items
  namespace :customers do
    resources :items, only: [:index, :show]
  end

  scope module: :customers do
    #customers_1
    get 'customers/:id/leave' => 'customers#leave', as: :leave
    patch 'customers/out' => 'customers#out'

    #orders_1
    get '/customers/:customer_id/orders/thanks' => 'orders#thanks'
    post '/customers/:customer_id/orders/confirm' => 'orders#confirm', as: :confirm
    get '/customers/:customer_id/orders/:id/complete' => 'orders#complete', as: :complete

    #customers_2
    resources :customers, only: [:show, :edit, :update] do
      #cart_items
      delete 'cart_items' => 'cart_items#all_destroy'
      resources :cart_items, only: [:create, :index, :update, :destroy]
      
      #shipping_addresses
      resources :shipping_addresses , only: [:index,  :create, :edit, :update, :destroy]
      
      #orders_2
      resources :orders, only: [:index, :show, :new, :create]
    end
    
    
  end
  
  
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :customer
	validates :number, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items # 中間テーブルのアソシエーション定義
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_furigana, presence: true
  validates :first_furigana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true, uniqueness: true


  enum status: { unavailable: 0, available: 1}
  validates :status, inclusion: { in: Customer.statuses.keys }

  def active_for_authentication?
    super && (self.status == "available")
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
	validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	has_many :customers, through: :cart_items # 中間テーブルのアソシエーション定義
	has_many :order_items, dependent: :destroy
	has_many :orders, through: :order_items # 中間テーブルのアソシエーション定義

	validates :name, presence: true
	validates :content, presence: true
	validates :no_tax_price, presence: true
	
	enum sale_status: { unavailable: 0, available: 1}
	validates :sale_status, inclusion: { in: Item.sale_statuses.keys }
  
	attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items # 中間テーブルのアソシエーション定義

  validates :address, presence: true
  validates :address_name, presence: true
  validates :postal_code, presence: true

  enum payment: { credit_card: 0, bank_transfer: 1 }
  validates :payment, inclusion: { in: Order.payments.keys }

  enum status: { waiting_payment: 0, payment_confirm: 1, making: 2, ready_to_ship: 3, shipped: 4 }
  validates :status, inclusion: { in: Order.statuses.keys }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :item
	validates :number, presence: true
	enum item_status: { not_start: 0, standby_making: 1, making: 2, making_finish: 3 }
	validates :item_status, inclusion: { in: OrderItem.item_statuses.keys }
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer 

  validates :address_name, presence: true
  validates :shipping_address, presence: true
  validates :shipping_postal_code, presence: true

  def registered_shipping_address
  	self.shipping_postal_code + "　" + self.shipping_address + "　" + self.address_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
      when Owner
        owners_top_path
      when Customer
        root_path
      end
    end

    def after_sign_out_path_for(resource)
      case resource
      when :owner
        new_owner_session_path
      when :customer
        root_path
      end
    end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_furigana, :first_furigana, :postal_code, :address, :telephone_number])
    end

    def update_resource(resource, params)
        resource.update_without_password(params)
    end

    def after_update_path_for(resource)
      customer_path(resource)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @genres = Genre.where(status: true)
    @items = Item.find(1, 2, 3, 4)
  end

	def about
	end
end

app/controllers/owners_controller 2.rb
class OwnersController < ApplicationController

def top
end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def top
		if Order.where(created_at: Time.zone.now.all_day).present?
			@data = Order.where(created_at: Time.zone.now.all_day).count
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y/%m/%d")
  end
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners/genres_helper.rb
module Owners::GenresHelper
end

app/helpers/owners/items_helper 2.rb
module Owners::ItemsHelper
end

app/helpers/owners/items_helper.rb
module Owners::ItemsHelper
end

app/helpers/owners/orders_helper.rb
module Owners::OrdersHelper
end

app/helpers/owners_helper 2.rb
module OwnersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/home/about.html.erb
<div>
	<h1 class="ec_about_title">About</h1>
</div>

<div>
	<h2 class="ec_about_text">
		ながのCakeは全国発送可能なケーキ屋さんです。<br>
		お子様からお年寄りの方までお召し上がりいただけるよう、<br>
		様々なバリエーションをご用意しております。<br>
		また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
		ぜひご注文ください。
	</h2>
</div>

<div class="ec_about_image"></div>

app/views/home/top.html.erb
<div class="row">
  <div class="col-xs-3">
    <nav class="genre_nav navbar navbar-dark bg-dark">
      <div class="genre_nav_title">
        <h3>ジャンル検索</h3>
      </div>
      <div class="genre_nav_list">
        <ul>
          <% @genres.each do |genre| %>
            <%= link_to customers_items_path(:genre_nav => genre.id) do %>
              <li>
                <%= genre.name %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <div class="recommend_items">
    <div class="col-xs-9">
      <div class="welcome_message">
        <p>
          ようこそ、NaganoCakeへ！<br>
          このサイトは、ケーキ販売のECサイトになります。<br>
          会員でない方も商品の閲覧はできますが、<br>
          購入には会員登録が必要になります。
        </p>
      </div>
      <div class="item_list">
        <div class="item_title">
          <div class="item_title_name">
            <h2>オススメ商品</h2>
          </div>
        </div>
        <div class="row item_list">
          <% @items.each do |item| %>
            <%= link_to customers_item_path(item.id) do %>
              <div class="item_list col-xs-3">
                <div class="item_image">
                  <%= attachment_image_tag(item, :image, size: "200x180", fallback: "no_image.jpg") %>
                </div>
                <div class="item_name">
                  <%= item.name %>
                </div>
                <div class="item_price">
                  ¥<%= ( item.no_tax_price * 1.1 ).floor %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="ec_top_item_index">
        <%= link_to "もっと見る＞", customers_items_path %>
      </div>
    </div>
  </div>
</div>