config/routes.rb
Rails.application.routes.draw do
  #devise
  devise_for :owners, controller: {
    sessions: "owners/sessions",
    passwords: "owners/passwords",
    registrations: "owners/registration"
    }

  devise_for :customers, controller: {
    sessions: "customers/sessions",
    passwords: "customers/passwords",
    registrations: "customers/registration"
    }
  
  #top,about
  get 'owners/top' => 'owners#top'
  root 'home#top'
  get 'home/about' => 'home#about'


  #owner_side

  namespace :owners do
    #items
    resources :items, only: [:new, :create, :edit, :update]
    get 'items/index_owner'    =>  'items#index_owner'
    get 'items/:id/show_owner' =>  'items#show_owner'
    
    #genre
    resources :genres, only: [:index, :create, :edit, :update]
    
    #customers
    resources :customers, only: [:index]
    get 'customers/:id/show_owner'      => 'customers#show_owner' , as: :show_owner_costomer
    get 'customers/:id/edit/edit_owner' => 'customers#edit_owner', as: :edit_owner_costomer
    patch 'customers/:id/update_owner'  => 'customers#update_owner', as: :update_owner_costomer

    #orders
    resources :orders, only: [:index, :show, :update]
    patch 'order/:id/update_order' => 'orders#update_order',as: :update_owner_order
  end


  #customer_side
  
  #items
  namespace :customers do
    resources :items, only: [:index, :show]
  end

  scope module: :customers do
    #customers_1
    get 'customers/:id/leave' => 'customers#leave', as: :leave
    patch 'customers/out' => 'customers#out'

    #orders_1
    get '/customers/:customer_id/orders/thanks' => 'orders#thanks'
    post '/customers/:customer_id/orders/confirm' => 'orders#confirm', as: :confirm
    get '/customers/:customer_id/orders/:id/complete' => 'orders#complete', as: :complete

    #customers_2
    resources :customers, only: [:show, :edit, :update] do
      #cart_items
      delete 'cart_items' => 'cart_items#all_destroy'
      resources :cart_items, only: [:create, :index, :update, :destroy]
      
      #shipping_addresses
      resources :shipping_addresses , only: [:index,  :create, :edit, :update, :destroy]
      
      #orders_2
      resources :orders, only: [:index, :show, :new, :create]
    end
    
    
  end
  
  
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items # 中間テーブルのアソシエーション定義

  validates :address, presence: true
  validates :address_name, presence: true
  validates :postal_code, presence: true

  enum payment: { credit_card: 0, bank_transfer: 1 }
  validates :payment, inclusion: { in: Order.payments.keys }

  enum status: { waiting_payment: 0, payment_confirm: 1, making: 2, ready_to_ship: 3, shipped: 4 }
  validates :status, inclusion: { in: Order.statuses.keys }
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders
  end

  def create
    if current_customer.cart_items.exists?
      #お届け先によって保存内容を場合分け
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.address_name = params[:order][:address_name]
      @order.billing_amount = params[:order][:billing_amount]
      @order.save

      #今回使われた配送先が新規のものであれば、配送先に新規登録
      if ShippingAddress.find_by(shipping_address: @order.address).nil? && current_customer.address != @order.address
        @shipping_address = ShippingAddress.new
        @shipping_address.shipping_postal_code = @order.postal_code
        @shipping_address.shipping_address = @order.address
        @shipping_address.address_name = @order.address_name
        @shipping_address.customer_id = current_customer.id
        @shipping_address.save
      end

      #cart_itemsの内容をorder_itemsに新規登録
      current_customer.cart_items.each do |cart_item|
        order_item = @order.order_items.build
        order_item.order_id = @order.id
        order_item.item_id = cart_item.item_id
        order_item.number = cart_item.number
        order_item.buy_price = (cart_item.item.no_tax_price * 1.1).floor
        order_item.save
        cart_item.destroy #order_itemsに新規登録後はカートの中を空にする
      end
      redirect_to complete_path(current_customer.id, @order.id)
    else
      redirect_to root_path
      flash[:danger] = "カートが空です。"
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @items = @order.items
  end

  def new
    @order = Order.new
    @shipping_addresses = ShippingAddress.where(customer_id: current_customer.id)
  end

  def confirm    
    #注文情報入力画面でのお届け先選択によって分岐
    @order = Order.new
    if params[:choice_shipping_address] == "my_address"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.address_name = current_customer.last_name + current_customer.first_name
      @cart_items = current_customer.cart_items

    elsif params[:choice_shipping_address] == "registered_address"
      @shipping_address = ShippingAddress.find(params[:choice_pulldown])
      @order.postal_code = @shipping_address.shipping_postal_code
      @order.address = @shipping_address.shipping_address
      @order.address_name = @shipping_address.address_name
      @cart_items = current_customer.cart_items

    else
      @order.postal_code = params[:postal_code]
      @order.address = params[:address]
      @order.address_name = params[:address_name]
      @cart_items = current_customer.cart_items
    end
  end
  
  def complete
  end

  private
  def order_params
    params.require(:order).permit(:payment, :address_name, :address, :postal_code, :choice_pulldown)
  end
end

app/controllers/owners/customers_controller 2.rb
class Owners::CustomersController < ApplicationController

def index
end

def show_owner
end

def edit_owner
end

def update_owner
end

end

app/controllers/owners/customers_controller.rb
class Owners::CustomersController < ApplicationController
  before_action :authenticate_owner!

def index
  @customer = Customer.all
  @customers = Customer.all.page(params[:page]).per(10)
end

def show_owner
	@customer = Customer.find(params[:id])
end

def edit_owner
  @customer = Customer.find(params[:id])
end

def update_owner
  @customer = Customer.find(params[:id])
  @customer.update(customers_params)
  if @customer.save
    redirect_to owners_customers_path
    end
end

private
    def customers_params
      params.require(:customer).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :postal_code,:address, :telephone_number, :status)
    end
end

app/controllers/owners/genres_controller 2.rb
class Owners::GenresController < ApplicationController

def index
end

def create
end

def edit
end

def update
end

end

app/controllers/owners/genres_controller.rb
class Owners::GenresController < ApplicationController
  before_action :authenticate_owner!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンル登録完了しました！"
      redirect_to owners_genres_path
    else
      flash[:notice] = "更新に失敗しました。入力を確認してください。"
      @genre = Genre.all
      redirect_to owners_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.save
      flash[:notice] = "カテゴリーを更新しました"
      redirect_to owners_genres_path# 一覧画面へリダイレクト
    else
      render :edit

    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/owners/items_controller 2.rb
class Owners::ItemsController < ApplicationController

def new
end

def create
end

def index_owner
end

def show_owner
end

def edit
end

def update
end

end

app/controllers/owners/items_controller.rb
class Owners::ItemsController < ApplicationController
  before_action :authenticate_owner!

  def new
    @item = Item.new
    @genres = Genre.where(status: true)
  end

  def create
    @item = Item.new(items_params)
    if @item.save
      flash[:notice] = "商品登録完了しました！"
      redirect_to owners_path(@item)
    else
      @genres = Genre.where(status: true)
      render 'new'
    end
  end

  def index_owner
    @item = Item.all
    @items = Item.all.page(params[:page]).per(10)
  end

  def show_owner
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(items_params)
    if @item.save
    flash[:notice] = "商品登録更新しました！"
    redirect_to owners_items_index_owner_path# 一覧画面へリダイレクト
    
  end
  end


  private
  def items_params
    params.require(:item).permit(:name, :content, :no_tax_price, :sale_status, :image ,:genre_id)
  end
end

app/controllers/owners/orders_controller 2.rb
class Owners::OrdersController < ApplicationController

def index
end

def show
end

def update_order
end

def update
end

end

app/controllers/owners/orders_controller.rb
class Owners::OrdersController < ApplicationController
  before_action :authenticate_owner!

	def index
		case params[:order_index_source]
			when "from_header"
				@orders = Order.all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_top"
				@orders = Order.where(created_at: Time.zone.now.all_day).page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
			when "from_show_owner"
				@orders = Order.where(customer_id: params[:customer_source]).all.page(params[:page]).per(10)
				@order_index_source = params[:order_index_source]
		end
	end

	def show
		@order = Order.find(params[:id])
		@sum = 0
	end

	def update
		@order = Order.find(params[:id])
		@order.update(orders_params)
			if params[:order][:status] == "payment_confirm"
				@order.order_items.each do |order_item|
					order_item.standby_making!
				end
				flash[:notice] = "注文の入金が確認できたので、商品の製品ステータスを製作待ちに更新しました！"
			else
				flash[:notice] = "注文ステータスを更新しました！"
			end
		redirect_to owners_order_path(@order.id)
	end
	
	def update_order
		@order = Order.find(params[:order_item][:order_id])
		@order_item = OrderItem.find(params[:id])
		@order_items = OrderItem.where(order_id: params[:order_item][:order_id])		
		@order_item.item_status = params[:order_item][:item_status]
		@order_item.update(order_item_params)
		if @order_items.where(item_status: "making").count == 1 && @order_items.where(item_status: "making_finish").count != @order_items.count - 1
			@order.making!
			flash[:notice] = "製作ステータスおよび注文ステータスを製作中に更新しました！"
		end
		if @order_items.where(item_status: "making_finish").count == @order_items.count
			@order.ready_to_ship!
			flash[:notice] = "注文された商品の製作が完了したので、注文ステータスを発送準備中に更新しました！"
		else
			flash[:notice] = "商品の製作ステータスを更新しました！"
		end			
		redirect_to owners_order_path(@order.id)
	end

	private
	def orders_params
		params.require(:order).permit(:customer_id, :postage, :billing_amount, :payment, :address, :postal_code, :status, :address_name)
	end
	def order_item_params
		params.require(:order_item).permit(:item_status)
	end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def top
		if Order.where(created_at: Time.zone.now.all_day).present?
			@data = Order.where(created_at: Time.zone.now.all_day).count
		end
	end

end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/helpers/owners/customers_helper 2.rb
module Owners::CustomersHelper
end

app/helpers/owners/customers_helper.rb
module Owners::CustomersHelper
end

app/helpers/owners/genres_helper 2.rb
module Owners::GenresHelper
end

app/helpers/owners/genres_helper.rb
module Owners::GenresHelper
end

app/helpers/owners/items_helper 2.rb
module Owners::ItemsHelper
end

app/helpers/owners/items_helper.rb
module Owners::ItemsHelper
end

app/helpers/owners/orders_helper 2.rb
module Owners::OrdersHelper
end

app/views/owners/orders/index.html.erb
<h3 class="ow_ganre_title">注文履歴一覧</h3>
<!-- 注文履歴一覧テーブル -->
<div class="row" style="margin-top:30px;">
	<div class="col-xs-10 ">
		<table class="table table-hover table-bordered table-condensed">
			<thead>
				<tr class="active">
					<th>購入日時</th>
						<th>購入者</th>
					<th>注文個数</th>
					<th>注文ステータス</th>
				</tr>
			</thead>

			<tbody>
				<% @orders.each do |order| %>
					<tr>
						<td>
							<%= link_to order.created_at. strftime('%Y/%m/%d/%R:%S') , owners_order_path(order) %>
						</td>
						<td>
							<%= order.customer.last_name + order.customer.first_name %>
						</td>
						<td>
							<% sum = 0 %>
							<% order.order_items.each do |order_item| %>
								<% sum = sum + order_item.number%>
							<% end %>
							<%= sum %>
						</td>
						<td>
							<% case order.status %>
								<% when "waiting_payment" %>
									入金待ち
								<% when "payment_confirm" %>
									入金確認
								<% when "making" %>
									製作中
								<% when "ready_to_ship" %>
									発送準備中
								<% when "shipped" %>
									発送済み
							<% end %>
							</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="paginate">
			<%= paginate @orders %>
			<%= hidden_field_tag :order_index_source => @order_index_source %>
		</div>
	</div>
</div>

app/views/owners/orders/show.html.erb
<h3 class="ow_ganre_title">注文履歴詳細</h3>
  <div class="row" style="margin-top:30px;">
    <div class = "col-lg-9">
      <br>
      <!-- 購入者情報 -->
      <th>購入者</th>
        <td>
          <%= link_to owners_show_owner_costomer_path(@order.customer_id) do %>
            <%= @order.customer.last_name %>
            <%= @order.customer.first_name %>
          <% end %>
        </td>
      <br>
        <th>配送先</th>
        <td>〒<%= @order.postal_code %><%= @order.address %></td>
      <br>
        <td><%= @order.address_name %></td>
      <br>
        <th>支払方法</th>
        <% case @order.payment %>
          <% when "credit_card" %>
            クレジットカード
          <% when "bank_transfer" %>
            銀行振込
        <% end %>

      <!-- 注文商品一覧 -->
      <%= form_with(model: @order, url: owners_order_path(@order), method: :patch,local:true ) do |f| %>
        <br><%= f.label :sale_status, "注文ステータス" %>
        <%= f.select :status, [["入金待ち","waiting_payment"], ["入金確認","payment_confirm"],["製作中","making"],["発送準備中","ready_to_ship"],["発送済み","shipped"]], include_blank: "選択して下さい"  %>
        <%= f.submit'更新',class: "btn btn-primary px-3" %>
      <% end %>
      <table class="table table-hover table-bordered table-inverse">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
      <tbody>

        <% @order.order_items.each do |order_item| %>
          <tr>
            <td>
              <%= order_item.item.name %>
            </td>
            <td>
              <%= (order_item.item.no_tax_price * 1.1).floor %>
            </td>
            <td>
              <%= order_item.number %>
            </td>
            <td>
              <%= ((order_item.number * order_item.item.no_tax_price)* 1.1).floor %>
            </td>
            <td>
              <%= form_with(model: order_item, url: owners_update_owner_order_path(order_item), method: :patch, local:true)  do |f| %>
                <%= f.select :item_status, [["着手不可", "not_start"],["製作待ち", "standby_making"],["製作中", "making"],["製作完了", "making_finish"]],include_blank: "選択して下さい" %>
                <%= f.hidden_field :order_id, value: @order.id  %>
                <%= f.submit "更新", class: "btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- 注文金額一覧 -->
  <div class = "col-lg-3">
      <table class="table table-hover table-bordered table-condensed">
        <tr>
          <th>商品合計</th>
          <td>
            <% @order.order_items.each do |order_item| %>
              <% sub_total = ((order_item.number * order_item.item.no_tax_price)* 1.1).floor %>
              <% @sum += sub_total %>
            <% end %>
            ¥<%= @sum %>
          </td>
        </tr>
        <tr>
          <th>送料</th>
          <td>¥800</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td>
            ¥<%= (@sum + 800).floor %>
          </td>
        </tr>
        </table>
  </div>
</div>